import React, {useState, useEffect} from 'react';
import StockBox from '../components/StockBox.jsx'

const StockList = (props) => {
  const [state, setState] = useState({counter:0});
  const snp500 = [
    ["Apple Inc.",	 "AAPL"],
    ["Microsoft Corporation",	 "MSFT"],
    ["Amazon.com Inc.",	 "AMZN"],
    ["Facebook Inc. Class A",	 "FB"],
    ["Berkshire Hathaway Inc. Class B",	 "BRK.B"],
    ["JPMorgan Chase & Co.",	 "JPM"],
    ["Alphabet Inc. Class C",	 "GOOG"],
    ["Alphabet Inc. Class A",	 "GOOGL"],
    ["Johnson & Johnson",	 "JNJ"],
    ["Exxon Mobil Corporation",	 "XOM"],
    ["Visa Inc. Class A",	 "V"],
    ["Procter & Gamble Company",	 "PG"],
    ["AT&T Inc.",	 "T"],
    ["Bank of America Corp",	 "BAC"],
    ["Intel Corporation",	 "INTC"],
    ["Home Depot Inc.",	 "HD"],
    ["Verizon Communications Inc.",	 "VZ"],
    ["Mastercard Incorporated Class A",	 "MA"],
    ["UnitedHealth Group Incorporated",	 "UNH"],
    ["Walt Disney Company",	 "DIS"],
    ["Chevron Corporation",	 "CVX"],
    ["Wells Fargo & Company",	 "WFC"],
    ["Merck & Co. Inc.",	 "MRK"],
    ["Cisco Systems Inc.",	 "CSCO"],
    ["Pfizer Inc.",	 "PFE"],
    ["Comcast Corporation Class A",	 "CMCSA"],
    ["Coca-Cola Company",	 "KO"],
    ["Boeing Company",	 "BA"],
    ["PepsiCo Inc.",	 "PEP"],
    ["Citigroup Inc.",	 "C"],
    ["Walmart Inc.",	 "WMT"],
    ["Abbott Laboratories",	 "ABT"],
    ["McDonald's Corporation",	 "MCD"],
    ["Medtronic Plc",	 "MDT"],
    ["Adobe Inc.",	 "ADBE"],
    ["salesforce.com inc.",	 "CRM"],
    ["Costco Wholesale Corporation",	 "COST"],
    ["Amgen Inc.",	 "AMGN"],
    ["Honeywell International Inc.",	 "HON"],
    ["Philip Morris International Inc.",	 "PM"],
    ["Netflix Inc.",	 "NFLX"],
    ["NVIDIA Corporation",	 "NVDA"],
    ["Union Pacific Corporation",	 "UNP"],
    ["Broadcom Inc.",	 "AVGO"],
    ["Oracle Corporation",	 "ORCL"],
    ["International Business Machines Corporation",	 "IBM"],
    ["AbbVie Inc.",	 "ABBV"],
    ["United Technologies Corporation",	 "UTX"],
    ["Accenture Plc Class A",	 "ACN"],
    ["PayPal Holdings Inc",	 "PYPL"],
    ["Thermo Fisher Scientific Inc.",	 "TMO"],
    ["NIKE Inc. Class B",	 "NKE"],
    ["Texas Instruments Incorporated",	 "TXN"],
    ["Linde plc",	 "LIN"],
    ["QUALCOMM Incorporated",	 "QCOM"],
    ["NextEra Energy Inc.",	 "NEE"],
    ["3M Company",	 "MMM"],
    ["General Electric Company",	 "GE"],
    ["Starbucks Corporation",	 "SBUX"],
    ["Eli Lilly and Company",	 "LLY"],
    ["Lockheed Martin Corporation",	 "LMT"],
    ["Bristol-Myers Squibb Company",	 "BMY"],
    ["CVS Health Corporation",	 "CVS"],
    ["American Tower Corporation",	 "AMT"],
    ["Lowe's Companies Inc.",	 "LOW"],
    ["United Parcel Service Inc. Class B",	 "UPS"],
    ["Danaher Corporation",	 "DHR"],
    ["Altria Group Inc",	 "MO"],
    ["U.S. Bancorp",	 "USB"],
    ["Caterpillar Inc.",	 "CAT"],
    ["American Express Company",	 "AXP"],
    ["Fidelity National Information Services Inc.",	 "FIS"],
    ["Gilead Sciences Inc.",	 "GILD"],
    ["Booking Holdings Inc.",	 "BKNG"],
    ["Celgene Corporation",	 "CELG"],
    ["Charter Communications Inc. Class A",	 "CHTR"],
    ["Mondelez International Inc. Class A",	 "MDLZ"],
    ["Goldman Sachs Group Inc.",	 "GS"],
    ["TJX Companies Inc",	 "TJX"],
    ["Anthem Inc.",	 "ANTM"],
    ["CME Group Inc. Class A",	 "CME"],
    ["Automatic Data Processing Inc.",	 "ADP"],
    ["Cigna Corporation",	 "CI"],
    ["Chubb Limited",	 "CB"],
    ["PNC Financial Services Group Inc.",	 "PNC"],
    ["Intuit Inc.",	 "INTU"],
    ["Duke Energy Corporation",	 "DUK"],
    ["ConocoPhillips",	 "COP"],
    ["Dominion Energy Inc",	 "D"],
    ["Becton Dickinson and Company",	 "BDX"],
    ["Stryker Corporation",	 "SYK"],
    ["Intuitive Surgical Inc.",	 "ISRG"],
    ["Southern Company",	 "SO"],
    ["S&P Global Inc.",	 "SPGI"],
    ["Fiserv Inc.",	 "FISV"],
    ["Morgan Stanley",	 "MS"],
    ["Raytheon Company",	 "RTN"],
    ["CSX Corporation",	 "CSX"],
    ["Allergan plc",	 "AGN"],
    ["Zoetis Inc. Class A",	 "ZTS"],
    ["BlackRock Inc.",	 "BLK"],
    ["Colgate-Palmolive Company",	 "CL"],
    ["Target Corporation",	 "TGT"],
    ["Boston Scientific Corporation",	 "BSX"],
    ["Deere & Company",	 "DE"],
    ["Prologis Inc.",	 "PLD"],
    ["Crown Castle International Corp",	 "CCI"],
    ["Northrop Grumman Corporation",	 "NOC"],
    ["Phillips 66",	 "PSX"],
    ["Micron Technology Inc.",	 "MU"],
    ["DuPont de Nemours Inc.",	 "DD"],
    ["Biogen Inc.",	 "BIIB"],
    ["Marsh & McLennan Companies Inc.",	 "MMC"],
    ["Illinois Tool Works Inc.",	 "ITW"],
    ["Applied Materials Inc.",	 "AMAT"],
    ["Norfolk Southern Corporation",	 "NSC"],
    ["Intercontinental Exchange Inc.",	 "ICE"],
    ["Global Payments Inc.",	 "GPN"],
    ["Charles Schwab Corporation",	 "SCHW"],
    ["Vertex Pharmaceuticals Incorporated",	 "VRTX"],
    ["Air Products and Chemicals Inc.",	 "APD"],
    ["Schlumberger NV",	 "SLB"],
    ["Edwards Lifesciences Corporation",	 "EW"],
    ["General Motors Company",	 "GM"],
    ["American International Group Inc.",	 "AIG"],
    ["Simon Property Group Inc.",	 "SPG"],
    ["Ecolab Inc.",	 "ECL"],
    ["Sherwin-Williams Company",	 "SHW"],
    ["Capital One Financial Corporation",	 "COF"],
    ["Aon plc",	 "AON"],
    ["Kimberly-Clark Corporation",	 "KMB"],
    ["Emerson Electric Co.",	 "EMR"],
    ["Walgreens Boots Alliance Inc",	 "WBA"],
    ["Equinix Inc.",	 "EQIX"],
    ["American Electric Power Company Inc.",	 "AEP"],
    ["Marathon Petroleum Corporation",	 "MPC"],
    ["L3Harris Technologies Inc",	 "LHX"],
    ["Exelon Corporation",	 "EXC"],
    ["EOG Resources Inc.",	 "EOG"],
    ["Illumina Inc.",	 "ILMN"],
    ["Waste Management Inc.",	 "WM"],
    ["General Dynamics Corporation",	 "GD"],
    ["Humana Inc.",	 "HUM"],
    ["Bank of New York Mellon Corporation",	 "BK"],
    ["Progressive Corporation",	 "PGR"],
    ["Valero Energy Corporation",	 "VLO"],
    ["BB&T Corporation",	 "BBT"],
    ["Activision Blizzard Inc.",	 "ATVI"],
    ["Sysco Corporation",	 "SYY"],
    ["Analog Devices Inc.",	 "ADI"],
    ["Dow Inc.",	 "DOW"],
    ["Estee Lauder Companies Inc. Class A",	 "EL"],
    ["Ross Stores Inc.",	 "ROST"],
    ["Dollar General Corporation",	 "DG"],
    ["Aflac Incorporated",	 "AFL"],
    ["Baxter International Inc.",	 "BAX"],
    ["Lam Research Corporation",	 "LRCX"],
    ["Advanced Micro Devices Inc.",	 "AMD"],
    ["FedEx Corporation",	 "FDX"],
    ["MetLife Inc.",	 "MET"],
    ["Kinder Morgan Inc Class P",	 "KMI"],
    ["Sempra Energy",	 "SRE"],
    ["Eaton Corp. Plc",	 "ETN"],
    ["Prudential Financial Inc.",	 "PRU"],
    ["Marriott International Inc. Class A",	 "MAR"],
    ["HCA Healthcare Inc",	 "HCA"],
    ["Moody's Corporation",	 "MCO"],
    ["Allstate Corporation",	 "ALL"],
    ["Roper Technologies Inc.",	 "ROP"],
    ["Cognizant Technology Solutions Corporation Class A",	 "CTSH"],
    ["Ford Motor Company",	 "F"],
    ["Occidental Petroleum Corporation",	 "OXY"],
    ["Travelers Companies Inc.",	 "TRV"],
    ["O'Reilly Automotive Inc.",	 "ORLY"],
    ["Welltower Inc.",	 "WELL"],
    ["Johnson Controls International plc",	 "JCI"],
    ["Delta Air Lines Inc.",	 "DAL"],
    ["Autodesk Inc.",	 "ADSK"],
    ["Public Storage",	 "PSA"],
    ["Constellation Brands Inc. Class A",	 "STZ"],
    ["TE Connectivity Ltd.",	 "TEL"],
    ["Xcel Energy Inc.",	 "XEL"],
    ["Ingersoll-Rand Plc",	 "IR"],
    ["SunTrust Banks Inc.",	 "STI"],
    ["General Mills Inc.",	 "GIS"],
    ["Public Service Enterprise Group Inc",	 "PEG"],
    ["PPG Industries Inc.",	 "PPG"],
    ["Amphenol Corporation Class A",	 "APH"],
    ["Yum! Brands Inc.",	 "YUM"],
    ["Newmont Goldcorp Corporation",	 "NEM"],
    ["Equity Residential",	 "EQR"],
    ["AvalonBay Communities Inc.",	 "AVB"],
    ["Consolidated Edison Inc.",	 "ED"],
    ["Zimmer Biomet Holdings Inc.",	 "ZBH"],
    ["Cummins Inc.",	 "CMI"],
    ["HP Inc.",	 "HPQ"],
    ["ONEOK Inc.",	 "OKE"],
    ["Electronic Arts Inc.",	 "EA"],
    ["AutoZone Inc.",	 "AZO"],
    ["T. Rowe Price Group",	 "TROW"],
    ["Hilton Worldwide Holdings Inc",	 "HLT"],
    ["Southwest Airlines Co.",	 "LUV"],
    ["V.F. Corporation",	 "VFC"],
    ["IHS Markit Ltd.",	 "INFO"],
    ["WEC Energy Group Inc",	 "WEC"],
    ["eBay Inc.",	 "EBAY"],
    ["PACCAR Inc",	 "PCAR"],
    ["KLA Corporation",	 "KLAC"],
    ["State Street Corporation",	 "STT"],
    ["Discover Financial Services",	 "DFS"],
    ["TransDigm Group Incorporated",	 "TDG"],
    ["Motorola Solutions Inc.",	 "MSI"],
    ["Williams Companies Inc.",	 "WMB"],
    ["Dollar Tree Inc.",	 "DLTR"],
    ["Paychex Inc.",	 "PAYX"],
    ["Regeneron Pharmaceuticals Inc.",	 "REGN"],
    ["T-Mobile US Inc.",	 "TMUS"],
    ["SBA Communications Corp. Class A",	 "SBAC"],
    ["Parker-Hannifin Corporation",	 "PH"],
    ["FleetCor Technologies Inc.",	 "FLT"],
    ["Eversource Energy",	 "ES"],
    ["McKesson Corporation",	 "MCK"],
    ["FirstEnergy Corp.",	 "FE"],
    ["LyondellBasell Industries NV",	 "LYB"],
    ["IQVIA Holdings Inc",	 "IQV"],
    ["Aptiv PLC",	 "APTV"],
    ["Tyson Foods Inc. Class A",	 "TSN"],
    ["Digital Realty Trust Inc.",	 "DLR"],
    ["Realty Income Corporation",	 "O"],
    ["Xilinx Inc.",	 "XLNX"],
    ["Archer-Daniels-Midland Company",	 "ADM"],
    ["Alexion Pharmaceuticals Inc.",	 "ALXN"],
    ["Stanley Black & Decker Inc.",	 "SWK"],
    ["PPL Corporation",	 "PPL"],
    ["Willis Towers Watson Public Limited Company",	 "WLTW"],
    ["Corning Inc",	 "GLW"],
    ["Edison International",	 "EIX"],
    ["Agilent Technologies Inc.",	 "A"],
    ["Northern Trust Corporation",	 "NTRS"],
    ["Pioneer Natural Resources Company",	 "PXD"],
    ["Entergy Corporation",	 "ETR"],
    ["Verisk Analytics Inc",	 "VRSK"],
    ["Synchrony Financial",	 "SYF"],
    ["IDEXX Laboratories Inc.",	 "IDXX"],
    ["Microchip Technology Incorporated",	 "MCHP"],
    ["Twitter Inc.",	 "TWTR"],
    ["Hewlett Packard Enterprise Co.",	 "HPE"],
    ["M&T Bank Corporation",	 "MTB"],
    ["DTE Energy Company",	 "DTE"],
    ["Fifth Third Bancorp",	 "FITB"],
    ["Ventas Inc.",	 "VTR"],
    ["Hartford Financial Services Group Inc.",	 "HIG"],
    ["Monster Beverage Corporation",	 "MNST"],
    ["Las Vegas Sands Corp.",	 "LVS"],
    ["Centene Corporation",	 "CNC"],
    ["AMETEK Inc.",	 "AME"],
    ["Cintas Corporation",	 "CTAS"],
    ["Weyerhaeuser Company",	 "WY"],
    ["Ball Corporation",	 "BLL"],
    ["Kroger Co.",	 "KR"],
    ["Fortive Corp.",	 "FTV"],
    ["Cerner Corporation",	 "CERN"],
    ["American Water Works Company Inc.",	 "AWK"],
    ["Fastenal Company",	 "FAST"],
    ["Hershey Company",	 "HSY"],
    ["Rockwell Automation Inc.",	 "ROK"],
    ["United Airlines Holdings Inc.",	 "UAL"],
    ["MSCI Inc. Class A",	 "MSCI"],
    ["Ameriprise Financial Inc.",	 "AMP"],
    ["Essex Property Trust Inc.",	 "ESS"],
    ["Kraft Heinz Company",	 "KHC"],
    ["ResMed Inc.",	 "RMD"],
    ["Synopsys Inc.",	 "SNPS"],
    ["Boston Properties Inc.",	 "BXP"],
    ["Royal Caribbean Cruises Ltd.",	 "RCL"],
    ["McCormick & Company Incorporated",	 "MKC"],
    ["Corteva Inc",	 "CTVA"],
    ["VeriSign Inc.",	 "VRSN"],
    ["Keysight Technologies Inc",	 "KEYS"],
    ["KeyCorp",	 "KEY"],
    ["CDW Corp.",	 "CDW"],
    ["ANSYS Inc.",	 "ANSS"],
    ["Chipotle Mexican Grill Inc.",	 "CMG"],
    ["Align Technology Inc.",	 "ALGN"],
    ["Cadence Design Systems Inc.",	 "CDNS"],
    ["First Republic Bank",	 "FRC"],
    ["Clorox Company",	 "CLX"],
    ["CBRE Group Inc. Class A",	 "CBRE"],
    ["Hess Corporation",	 "HES"],
    ["Ameren Corporation",	 "AEE"],
    ["Vulcan Materials Company",	 "VMC"],
    ["Halliburton Company",	 "HAL"],
    ["Republic Services Inc.",	 "RSG"],
    ["Carnival Corporation",	 "CCL"],
    ["International Paper Company",	 "IP"],
    ["Mettler-Toledo International Inc.",	 "MTD"],
    ["Best Buy Co. Inc.",	 "BBY"],
    ["Omnicom Group Inc",	 "OMC"],
    ["Alexandria Real Estate Equities Inc.",	 "ARE"],
    ["D.R. Horton Inc.",	 "DHI"],
    ["Citizens Financial Group Inc.",	 "CFG"],
    ["Skyworks Solutions Inc.",	 "SWKS"],
    ["CMS Energy Corporation",	 "CMS"],
    ["Nucor Corporation",	 "NUE"],
    ["Regions Financial Corporation",	 "RF"],
    ["Arthur J. Gallagher & Co.",	 "AJG"],
    ["Cincinnati Financial Corporation",	 "CINF"],
    ["Healthpeak Properties Inc.",	 "PEAK"],
    ["Church & Dwight Co. Inc.",	 "CHD"],
    ["Copart Inc.",	 "CPRT"],
    ["Freeport-McMoRan Inc.",	 "FCX"],
    ["Lennar Corporation Class A",	 "LEN"],
    ["Maxim Integrated Products Inc.",	 "MXIM"],
    ["Laboratory Corporation of America Holdings",	 "LH"],
    ["Equifax Inc.",	 "EFX"],
    ["MGM Resorts International",	 "MGM"],
    ["Martin Marietta Materials Inc.",	 "MLM"],
    ["Amcor PLC",	 "AMCR"],
    ["Kellogg Company",	 "K"],
    ["Dover Corporation",	 "DOV"],
    ["Cardinal Health Inc.",	 "CAH"],
    ["CarMax Inc.",	 "KMX"],
    ["Western Digital Corporation",	 "WDC"],
    ["Celanese Corporation",	 "CE"],
    ["Huntington Bancshares Incorporated",	 "HBAN"],
    ["Teleflex Incorporated",	 "TFX"],
    ["Genuine Parts Company",	 "GPC"],
    ["Kansas City Southern",	 "KSU"],
    ["Mid-America Apartment Communities Inc.",	 "MAA"],
    ["WellCare Health Plans Inc.",	 "WCG"],
    ["Evergy Inc.",	 "EVRG"],
    ["Incyte Corporation",	 "INCY"],
    ["Concho Resources Inc.",	 "CXO"],
    ["Cooper Companies Inc.",	 "COO"],
    ["CenterPoint Energy Inc.",	 "CNP"],
    ["Principal Financial Group Inc.",	 "PFG"],
    ["Baker Hughes Company Class A",	 "BKR"],
    ["Ulta Beauty Inc",	 "ULTA"],
    ["Westinghouse Air Brake Technologies Corporation",	 "WAB"],
    ["CenturyLink Inc.",	 "CTL"],
    ["International Flavors & Fragrances Inc.",	 "IFF"],
    ["Gartner Inc.",	 "IT"],
    ["W.W. Grainger Inc.",	 "GWW"],
    ["Waters Corporation",	 "WAT"],
    ["NetApp Inc.",	 "NTAP"],
    ["Akamai Technologies Inc.",	 "AKAM"],
    ["UDR Inc.",	 "UDR"],
    ["NortonLifeLock Inc.",	 "NLOK"],
    ["Darden Restaurants Inc.",	 "DRI"],
    ["Xylem Inc.",	 "XYL"],
    ["Broadridge Financial Solutions Inc.",	 "BR"],
    ["Seagate Technology PLC",	 "STX"],
    ["Garmin Ltd.",	 "GRMN"],
    ["Extra Space Storage Inc.",	 "EXR"],
    ["Expedia Group Inc.",	 "EXPE"],
    ["Citrix Systems Inc.",	 "CTXS"],
    ["Quest Diagnostics Incorporated",	 "DGX"],
    ["Conagra Brands Inc.",	 "CAG"],
    ["Tiffany & Co.",	 "TIF"],
    ["Masco Corporation",	 "MAS"],
    ["Fortinet Inc.",	 "FTNT"],
    ["Loews Corporation",	 "L"],
    ["Expeditors International of Washington Inc.",	 "EXPD"],
    ["MarketAxess Holdings Inc.",	 "MKTX"],
    ["Take-Two Interactive Software Inc.",	 "TTWO"],
    ["Jacobs Engineering Group Inc.",	 "JEC"],
    ["Cboe Global Markets Inc",	 "CBOE"],
    ["DENTSPLY SIRONA Inc.",	 "XRAY"],
    ["AmerisourceBergen Corporation",	 "ABC"],
    ["FMC Corporation",	 "FMC"],
    ["Atmos Energy Corporation",	 "ATO"],
    ["Duke Realty Corporation",	 "DRE"],
    ["SVB Financial Group",	 "SIVB"],
    ["CBS Corporation Class B",	 "CBS"],
    ["Host Hotels & Resorts Inc.",	 "HST"],
    ["Hologic Inc.",	 "HOLX"],
    ["Diamondback Energy Inc.",	 "FANG"],
    ["Fox Corporation Class A",	 "FOXA"],
    ["Lincoln National Corporation",	 "LNC"],
    ["American Airlines Group Inc.",	 "AAL"],
    ["J.M. Smucker Company",	 "SJM"],
    ["Advance Auto Parts Inc.",	 "AAP"],
    ["Alliant Energy Corp",	 "LNT"],
    ["Wynn Resorts Limited",	 "WYNN"],
    ["Qorvo Inc.",	 "QRVO"],
    ["IDEX Corporation",	 "IEX"],
    ["Western Union Company",	 "WU"],
    ["Brown-Forman Corporation Class B",	 "BF.B"],
    ["Nasdaq Inc.",	 "NDAQ"],
    ["Leidos Holdings Inc.",	 "LDOS"],
    ["NVR Inc.",	 "NVR"],
    ["United Rentals Inc.",	 "URI"],
    ["AES Corporation",	 "AES"],
    ["Lamb Weston Holdings Inc.",	 "LW"],
    ["Eastman Chemical Company",	 "EMN"],
    ["Universal Health Services Inc. Class B",	 "UHS"],
    ["Jack Henry & Associates Inc.",	 "JKHY"],
    ["Tractor Supply Company",	 "TSCO"],
    ["Hormel Foods Corporation",	 "HRL"],
    ["Norwegian Cruise Line Holdings Ltd.",	 "NCLH"],
    ["Varian Medical Systems Inc.",	 "VAR"],
    ["Arconic Inc.",	 "ARNC"],
    ["Avery Dennison Corporation",	 "AVY"],
    ["Raymond James Financial Inc.",	 "RJF"],
    ["Hasbro Inc.",	 "HAS"],
    ["Regency Centers Corporation",	 "REG"],
    ["Textron Inc.",	 "TXT"],
    ["LKQ Corporation",	 "LKQ"],
    ["C.H. Robinson Worldwide Inc.",	 "CHRW"],
    ["Allegion PLC",	 "ALLE"],
    ["Comerica Incorporated",	 "CMA"],
    ["Packaging Corporation of America",	 "PKG"],
    ["Everest Re Group Ltd.",	 "RE"],
    ["Arista Networks Inc.",	 "ANET"],
    ["E*TRADE Financial Corporation",	 "ETFC"],
    ["Huntington Ingalls Industries Inc.",	 "HII"],
    ["Henry Schein Inc.",	 "HSIC"],
    ["J.B. Hunt Transport Services Inc.",	 "JBHT"],
    ["Vornado Realty Trust",	 "VNO"],
    ["CF Industries Holdings Inc.",	 "CF"],
    ["NRG Energy Inc.",	 "NRG"],
    ["Marathon Oil Corporation",	 "MRO"],
    ["Molson Coors Brewing Company Class B",	 "TAP"],
    ["WestRock Company",	 "WRK"],
    ["Discovery Inc. Class C",	 "DISCK"],
    ["Globe Life Inc.",	 "GL"],
    ["Noble Energy Inc.",	 "NBL"],
    ["NiSource Inc",	 "NI"],
    ["Pinnacle West Capital Corporation",	 "PNW"],
    ["ABIOMED Inc.",	 "ABMD"],
    ["Whirlpool Corporation",	 "WHR"],
    ["PulteGroup Inc.",	 "PHM"],
    ["PerkinElmer Inc.",	 "PKI"],
    ["Iron Mountain Inc.",	 "IRM"],
    ["BorgWarner Inc.",	 "BWA"],
    ["Snap-on Incorporated",	 "SNA"],
    ["Federal Realty Investment Trust",	 "FRT"],
    ["Devon Energy Corporation",	 "DVN"],
    ["Mohawk Industries Inc.",	 "MHK"],
    ["Zions Bancorporation N.A.",	 "ZION"],
    ["Kohl's Corporation",	 "KSS"],
    ["Apache Corporation",	 "APA"],
    ["National Oilwell Varco Inc.",	 "NOV"],
    ["F5 Networks Inc.",	 "FFIV"],
    ["Juniper Networks Inc.",	 "JNPR"],
    ["Interpublic Group of Companies Inc.",	 "IPG"],
    ["Mylan N.V.",	 "MYL"],
    ["Alaska Air Group Inc.",	 "ALK"],
    ["Kimco Realty Corporation",	 "KIM"],
    ["TechnipFMC Plc",	 "FTI"],
    ["Fortune Brands Home & Security Inc.",	 "FBHS"],
    ["DISH Network Corporation Class A",	 "DISH"],
    ["HollyFrontier Corporation",	 "HFC"],
    ["Franklin Resources Inc.",	 "BEN"],
    ["Viacom Inc. Class B",	 "VIAB"],
    ["Apartment Investment and Management Company Class A",	 "AIV"],
    ["Assurant Inc.",	 "AIZ"],
    ["Campbell Soup Company",	 "CPB"],
    ["Tapestry Inc.",	 "TPR"],
    ["Cabot Oil & Gas Corporation",	 "COG"],
    ["Newell Brands Inc",	 "NWL"],
    ["DXC Technology Co.",	 "DXC"],
    ["Albemarle Corporation",	 "ALB"],
    ["PVH Corp.",	 "PVH"],
    ["Pentair plc",	 "PNR"],
    ["Mosaic Company",	 "MOS"],
    ["A. O. Smith Corporation",	 "AOS"],
    ["Leggett & Platt Incorporated",	 "LEG"],
    ["FLIR Systems Inc.",	 "FLIR"],
    ["Xerox Holdings Corporation",	 "XRX"],
    ["SL Green Realty Corp.",	 "SLG"],
    ["Invesco Ltd.",	 "IVZ"],
    ["Nielsen Holdings Plc",	 "NLSN"],
    ["Robert Half International Inc.",	 "RHI"],
    ["Perrigo Co. Plc",	 "PRGO"],
    ["DaVita Inc.",	 "DVA"],
    ["People's United Financial Inc.",	 "PBCT"],
    ["Flowserve Corporation",	 "FLS"],
    ["Quanta Services Inc.",	 "PWR"],
    ["Harley-Davidson Inc.",	 "HOG"],
    ["Unum Group",	 "UNM"],
    ["Sealed Air Corporation",	 "SEE"],
    ["Ralph Lauren Corporation Class A",	 "RL"],
    ["Hanesbrands Inc.",	 "HBI"],
    ["Rollins Inc.",	 "ROL"],
    ["Fox Corporation Class B",	 "FOX"],
    ["Capri Holdings Limited",	 "CPRI"],
    ["IPG Photonics Corporation",	 "IPGP"],
    ["H&R Block Inc.",	 "HRB"],
    ["Macy's Inc",	 "M"],
    ["News Corporation Class A",	 "NWSA"],
    ["Discovery Inc. Class A",	 "DISCA"],
    ["Cimarex Energy Co.",	 "XEC"],
    ["Helmerich & Payne Inc.",	 "HP"],
    ["Affiliated Managers Group Inc.",	 "AMG"],
    ["Alliance Data Systems Corporation",	 "ADS"],
    ["L Brands Inc.",	 "LB"],
    ["Coty Inc. Class A",	 "COTY"],
    ["Nordstrom Inc.",	 "JWN"],
    ["Gap Inc.",	 "GPS"],
    ["Under Armour Inc. Class A",	 "UAA"],
    ["TripAdvisor Inc.",	 "TRIP"],
    ["Under Armour Inc. Class C",	 "UA"],
    ["Macerich Company",	 "MAC"],
    ["News Corporation Class B",	 "NWS"]   
  ];

  const arrToShow = [];
  const favList = [];
  let stocksToShow = 40;
  if(props.name !== ""){
    stocksToShow = snp500.length;
  }
  for(let i = 0; i < stocksToShow; i++){
    if(props.favList && props.favList.includes(snp500[i][1])){
      favList.push(<StockBox key={i} togglePopup ={props.togglePopup} stockName={snp500[i][0]} stockSymbol={snp500[i][1]}/>);
    }
    else if(snp500[i][0].toLowerCase().indexOf(props.name) !== -1){
      arrToShow.push(<StockBox key={i} togglePopup ={props.togglePopup} stockName={snp500[i][0]} stockSymbol={snp500[i][1]}/>);
    }
    else if(snp500[i][1].toLowerCase().indexOf(props.name) !== -1){
      arrToShow.push(<StockBox key={i} togglePopup ={props.togglePopup} stockName={snp500[i][0]} stockSymbol={snp500[i][1]}/>);
    }
  }

  return (
    <div>
      {favList.length !== 0 ? <div>Favorites {favList}</div> : null}
      {arrToShow}
    </div>
  );
}

export default StockList;
