import React from 'react';
import StockBox from '../components/StockBox'
const RenderList = (props) =>{
let arr_favs = [];
const snp500 = {
  "AAPL"                :                                                        "Apple Inc.",                                                                           
             "MSFT"                           :                                             "Microsoft Corporation",                                                                
       "AMZN"                     :                                                   "Amazon.com Inc."                                                                      ,
             "FB"                           :                                             "Facebook Inc. Class A"                                                            ,    
                       "BRK.B"                                     :                                   "Berkshire Hathaway Inc. Class B"                                     ,                 
            "JPM"                          :                                              "JPMorgan Chase & Co."                                                             ,    
             "GOOG"                           :                                             "Alphabet Inc. Class C"                                                          ,      
             "GOOGL"                           :                                             "Alphabet Inc. Class A"                                                         ,       
         "JNJ"                       :                                                 "Johnson & Johnson"                                                                   , 
               "XOM"                             :                                           "Exxon Mobil Corporation"                                                       ,       
         "V"                       :                                                 "Visa Inc. Class A"                                                                    ,
                "PG"                              :                                          "Procter & Gamble Company"                                                      ,       
 "T"               :                                                         "AT&T Inc."                                                                            ,
            "BAC"                          :                                              "Bank of America Corp"                                                             ,    
         "INTC"                       :                                                 "Intel Corporation"                                                                  ,  
       "HD"                     :                                                   "Home Depot Inc."                                                                      ,
                   "VZ"                                 :                                       "Verizon Communications Inc."                                                ,          
                       "MA"                                     :                                   "Mastercard Incorporated Class A"                                        ,              
                       "UNH"                                     :                                   "UnitedHealth Group Incorporated"                                       ,               
           "DIS"                         :                                               "Walt Disney Company"                                                               ,   
           "CVX"                         :                                               "Chevron Corporation"                                                               ,   
             "WFC"                           :               















































             "Wells Fargo & Company"                                                           ,     
        "MRK"                      :                                                  "Merck & Co. Inc."                                                                     ,
          "CSCO"                        :                                                "Cisco Systems Inc."                                                                ,   
   "PFE"                 :                                                       "Pfizer Inc."                                                                          ,
                   "CMCSA"                                 :                                       "Comcast Corporation Class A"                                             ,             
         "KO"                       :                                                 "Coca-Cola Company"                                                                    ,
      "BA"                    :                                                    "Boeing Company"                                                                       ,
    "PEP"                  :                                                      "PepsiCo Inc."                                                                         ,
      "C"                    :                                                    "Citigroup Inc."                                                                       ,
    "WMT"                  :                                                      "Walmart Inc."                                                                         ,
           "ABT"                         :                                               "Abbott Laboratories"                                                               ,   
              "MCD"                            :                                            "McDonald's Corporation"                                                         ,      
     "MDT"                   :                                                     "Medtronic Plc"                                                                        ,
  "ADBE"                :                                                        "Adobe Inc."                                                                           ,
           "CRM"                         :                                               "salesforce.com inc."                                                               ,   
                    "COST"                                  :                                      "Costco Wholesale Corporation"                                            ,             
  "AMGN"                :                                                        "Amgen Inc."                                                                           ,
                    "HON"                                  :                                      "Honeywell International Inc."                                             ,            
                        "PM"                                      :                                  "Philip Morris International Inc."                                      ,               
    "NFLX"                  :                                                      "Netflix Inc."                                                                         ,
          "NVDA"                        :                                                "NVIDIA Corporation"                                                                ,   
                 "UNP"                               :                                         "Union Pacific Corporation"                                                   ,         
     "AVGO"                   :                                                     "Broadcom Inc."                                                                        ,
          "ORCL"                        :                                                "Oracle Corporation"                                                                ,   
                                   "IBM"                                                 :                       "International Business Machines Corporation"               ,                           
   "ABBV"                 :                                                       "AbbVie Inc."                                                                          ,
                       "UTX"                                     :                                   "United Technologies Corporation"                                       ,               
             "ACN"                           :                                             "Accenture Plc Class A"                                                           ,     
           "PYPL"                         :                                               "PayPal Holdings Inc"                                                              ,    
                     "TMO"                                   :                                     "Thermo Fisher Scientific Inc."                                           ,             
         "NKE"                       :                                                 "NIKE Inc. Class B"                                                                   , 
                      "TXN"                                    :                                    "Texas Instruments Incorporated"                                         ,              
 "LIN"               :                                                         "Linde plc"                                                                            ,
             "QCOM"                           :                                             "QUALCOMM Incorporated"                                                          ,      
           "NEE"                         :                                               "NextEra Energy Inc."                                                               ,   
  "MMM"                :                                                        "3M Company"                                                                           ,
                "GE"                              :                                          "General Electric Company"                                                      ,       
             "SBUX"                           :                                             "Starbucks Corporation"                                                          ,      
             "LLY"                           :                                             "Eli Lilly and Company"                                                           ,     
                   "LMT"                                 :                                       "Lockheed Martin Corporation"                                               ,           
                    "BMY"                                  :                                      "Bristol-Myers Squibb Company"                                             ,            
              "CVS"                            :                                            "CVS Health Corporation"                                                         ,      
                  "AMT"                                :                                        "American Tower Corporation"                                                 ,          
             "LOW"                           :                                             "Lowe's Companies Inc."                                                           ,     
                          "UPS"                                        :                                "United Parcel Service Inc. Class B"                                 ,                  
           "DHR"                         :                                               "Danaher Corporation"                                                               ,   
        "MO"                      :                                                  "Altria Group Inc"                                                                     ,
    "USB"                  :                                                      "U.S. Bancorp"                                                                         ,
        "CAT"                      :                                                  "Caterpillar Inc."                                                                     ,
                "AXP"                              :                                          "American Express Company"                                                     ,        
                                   "FIS"                                                 :                       "Fidelity National Information Services Inc."               ,                           
            "GILD"                          :                                              "Gilead Sciences Inc."                                                            ,     
             "BKNG"                           :                                             "Booking Holdings Inc."                                                          ,      
           "CELG"                         :                                               "Celgene Corporation"                                                              ,    
                           "CHTR"                                         :                               "Charter Communications Inc. Class A"                              ,                    
                           "MDLZ"                                         :                               "Mondelez International Inc. Class A"                              ,                    
                "GS"                              :                                          "Goldman Sachs Group Inc."                                                      ,       
         "TJX"                       :                                                 "TJX Companies Inc"                                                                   , 
   "ANTM"                 :                                                       "Anthem Inc."                                                                          ,
              "CME"                            :                                            "CME Group Inc. Class A"                                                         ,      
                      "ADP"                                    :                                    "Automatic Data Processing Inc."                                         ,              
         "CI"                       :                                                 "Cigna Corporation"                                                                    ,
     "CB"                   :                                                     "Chubb Limited"                                                                        ,
                         "PNC"                                       :                                 "PNC Financial Services Group Inc."                                   ,                 
   "INTU"                 :                                                       "Intuit Inc."                                                                          ,
               "DUK"                             :                                           "Duke Energy Corporation"                                                       ,       
      "COP"                    :                                                    "ConocoPhillips"                                                                       ,
           "D"                         :                                               "Dominion Energy Inc"                                                                 , 
                    "BDX"                                  :                                      "Becton Dickinson and Company"                                             ,            
           "SYK"                         :                                               "Stryker Corporation"                                                               ,   
               "ISRG"                             :                                           "Intuitive Surgical Inc."                                                      ,        
        "SO"                      :                                                  "Southern Company"                                                                     ,
       "SPGI"                     :                                                   "S&P Global Inc."                                                                      ,
   "FISV"                 :                                                       "Fiserv Inc."                                                                          ,
      "MS"                    :                                                    "Morgan Stanley"                                                                       ,
        "RTN"                      :                                                  "Raytheon Company"                                                                     ,
       "CSX"                     :                                                   "CSX Corporation"                                                                      ,
    "AGN"                  :                                                      "Allergan plc"                                                                         ,
           "ZTS"                         :                                               "Zoetis Inc. Class A"                                                               ,   
      "BLK"                    :                                                    "BlackRock Inc."                                                                       ,
                 "CL"                               :                                         "Colgate-Palmolive Company"                                                    ,        
          "TGT"                        :                                                "Target Corporation"                                                                 ,  
                     "BSX"                                   :                                     "Boston Scientific Corporation"                                           ,             
       "DE"                     :                                                   "Deere & Company"                                                                      ,
     "PLD"                   :                                                     "Prologis Inc."                                                                        ,
                       "CCI"                                     :                                   "Crown Castle International Corp"                                       ,               
                    "NOC"                                  :                                      "Northrop Grumman Corporation"                                             ,            
   "PSX"                 :                                                       "Phillips 66"                                                                          ,
              "MU"                            :                                            "Micron Technology Inc."                                                          ,     
              "DD"                            :                                            "DuPont de Nemours Inc."                                                          ,     
   "BIIB"                 :                                                       "Biogen Inc."                                                                          ,
                       "MMC"                                     :                                   "Marsh & McLennan Companies Inc."                                       ,               
                "ITW"                              :                                          "Illinois Tool Works Inc."                                                     ,        
              "AMAT"                            :                                            "Applied Materials Inc."                                                        ,       
                    "NSC"                                  :                                      "Norfolk Southern Corporation"                                             ,            
                      "ICE"                                    :                                    "Intercontinental Exchange Inc."                                         ,              
            "GPN"                          :                                              "Global Payments Inc."                                                             ,    
                  "SCHW"                                :                                        "Charles Schwab Corporation"                                                ,           
                           "VRTX"                                         :                               "Vertex Pharmaceuticals Incorporated"                              ,                    
                       "APD"                                     :                                   "Air Products and Chemicals Inc."                                       ,               
       "SLB"                     :                                                   "Schlumberger NV"                                                                      ,
                        "EW"                                      :                                  "Edwards Lifesciences Corporation"                                      ,               
              "GM"                            :                                            "General Motors Company"                                                          ,     
                         "AIG"                                       :                                 "American International Group Inc."                                   ,                 
                 "SPG"                               :                                         "Simon Property Group Inc."                                                   ,         
   "ECL"                 :                                                       "Ecolab Inc."                                                                          ,
                "SHW"                              :                                          "Sherwin-Williams Company"                                                     ,        
                         "COF"                                       :                                 "Capital One Financial Corporation"                                   ,                 
"AON"             :                                                           "Aon plc"                                                                              ,
                  "KMB"                                :                                        "Kimberly-Clark Corporation"                                                 ,          
            "EMR"                          :                                              "Emerson Electric Co."                                                             ,    
                    "WBA"                                  :                                      "Walgreens Boots Alliance Inc"                                             ,            
    "EQIX"                  :                                                      "Equinix Inc."                                                                         ,
                            "AEP"                                          :                              "American Electric Power Company Inc."                             ,                    
                      "MPC"                                    :                                    "Marathon Petroleum Corporation"                                         ,              
                 "LHX"                               :                                         "L3Harris Technologies Inc"                                                   ,         
          "EXC"                        :                                                "Exelon Corporation"                                                                 ,  
          "EOG"                        :                                                "EOG Resources Inc."                                                                 ,  
     "ILMN"                   :                                                     "Illumina Inc."                                                                        ,
             "WM"                           :                                             "Waste Management Inc."                                                            ,    
                    "GD"                                  :                                      "General Dynamics Corporation"                                              ,           
   "HUM"                 :                                                       "Humana Inc."                                                                          ,
                           "BK"                                         :                               "Bank of New York Mellon Corporation"                                ,                  
               "PGR"                             :                                           "Progressive Corporation"                                                       ,       
                 "VLO"                               :                                         "Valero Energy Corporation"                                                   ,         
        "BBT"                      :                                                  "BB&T Corporation"                                                                     ,
                "ATVI"                              :                                          "Activision Blizzard Inc."                                                    ,         
         "SYY"                       :                                                 "Sysco Corporation"                                                                   , 
           "ADI"                         :                                               "Analog Devices Inc."                                                               ,   
"DOW"              :                                                          "Dow Inc."                                                                             ,
                           "EL"                                         :                               "Estee Lauder Companies Inc. Class A"                                ,                  
        "ROST"                      :                                                  "Ross Stores Inc."                                                                    , 
                  "DG"                                :                                        "Dollar General Corporation"                                                  ,         
          "AFL"                        :                                                "Aflac Incorporated"                                                                 ,  
                 "BAX"                               :                                         "Baxter International Inc."                                                   ,         
                "LRCX"                              :                                          "Lam Research Corporation"                                                    ,         
                   "AMD"                                 :                                       "Advanced Micro Devices Inc."                                               ,           
         "FDX"                       :                                                 "FedEx Corporation"                                                                   , 
    "MET"                  :                                                      "MetLife Inc."                                                                         ,
                 "KMI"                               :                                         "Kinder Morgan Inc Class P"                                                   ,         
     "SRE"                   :                                                     "Sempra Energy"                                                                        ,
       "ETN"                     :                                                   "Eaton Corp. Plc"                                                                      ,
                 "PRU"                               :                                         "Prudential Financial Inc."                                                   ,         
                           "MAR"                                         :                               "Marriott International Inc. Class A"                               ,                   
          "HCA"                        :                                                "HCA Healthcare Inc"                                                                 ,  
           "MCO"                         :                                               "Moody's Corporation"                                                               ,   
            "ALL"                          :                                              "Allstate Corporation"                                                             ,    
               "ROP"                             :                                           "Roper Technologies Inc."                                                       ,       
                                          "CTSH"                                                       :                "Cognizant Technology Solutions Corporation Class A"  ,                                
          "F"                        :                                                "Ford Motor Company"                                                                   ,
                        "OXY"                                      :                                  "Occidental Petroleum Corporation"                                     ,                
                "TRV"                              :                                          "Travelers Companies Inc."                                                     ,        
                "ORLY"                              :                                          "O'Reilly Automotive Inc."                                                    ,         
      "WELL"                    :                                                    "Welltower Inc."                                                                       ,
                          "JCI"                                        :                                "Johnson Controls International plc"                                 ,                  
            "DAL"                          :                                              "Delta Air Lines Inc."                                                             ,    
     "ADSK"                   :                                                     "Autodesk Inc."                                                                        ,
      "PSA"                    :                                                    "Public Storage"                                                                       ,
                         "STZ"                                       :                                 "Constellation Brands Inc. Class A"                                   ,                 
            "TEL"                          :                                              "TE Connectivity Ltd."                                                             ,    
        "XEL"                      :                                                  "Xcel Energy Inc."                                                                     ,
          "IR"                        :                                                "Ingersoll-Rand Plc"                                                                  , 
           "STI"                         :                                               "SunTrust Banks Inc."                                                               ,   
          "GIS"                        :                                                "General Mills Inc."                                                                 ,  
                           "PEG"                                         :                               "Public Service Enterprise Group Inc"                               ,                   
           "PPG"                         :                                               "PPG Industries Inc."                                                               ,   
                    "APH"                                  :                                      "Amphenol Corporation Class A"                                             ,            
        "YUM"                      :                                                  "Yum! Brands Inc."                                                                     ,
                    "NEM"                                  :                                      "Newmont Goldcorp Corporation"                                             ,            
          "EQR"                        :                                                "Equity Residential"                                                                 ,  
                  "AVB"                                :                                        "AvalonBay Communities Inc."                                                 ,          
                "ED"                              :                                          "Consolidated Edison Inc."                                                      ,       
                   "ZBH"                                 :                                       "Zimmer Biomet Holdings Inc."                                               ,           
    "CMI"                  :                                                      "Cummins Inc."                                                                         ,
"HPQ"             :                                                           "HP Inc."                                                                              ,
  "OKE"                :                                                        "ONEOK Inc."                                                                           ,
            "EA"                          :                                              "Electronic Arts Inc."                                                              ,   
     "AZO"                   :                                                     "AutoZone Inc."                                                                        ,
           "TROW"                         :                                               "T. Rowe Price Group"                                                              ,    
                     "HLT"                                   :                                     "Hilton Worldwide Holdings Inc"                                           ,             
              "LUV"                            :                                            "Southwest Airlines Co."                                                         ,      
        "VFC"                      :                                                  "V.F. Corporation"                                                                     ,
       "INFO"                     :                                                   "IHS Markit Ltd."                                                                      ,
            "WEC"                          :                                              "WEC Energy Group Inc"                                                             ,    
 "EBAY"               :                                                         "eBay Inc."                                                                            ,
  "PCAR"                :                                                        "PACCAR Inc"                                                                           ,
       "KLAC"                     :                                                   "KLA Corporation"                                                                      ,
                "STT"                              :                                          "State Street Corporation"                                                     ,        
                   "DFS"                                 :                                       "Discover Financial Services"                                               ,           
                    "TDG"                                  :                                      "TransDigm Group Incorporated"                                             ,            
               "MSI"                             :                                           "Motorola Solutions Inc."                                                       ,       
               "WMB"                             :                                           "Williams Companies Inc."                                                       ,       
        "DLTR"                      :                                                  "Dollar Tree Inc."                                                                    , 
    "PAYX"                  :                                                      "Paychex Inc."                                                                         ,
                      "REGN"                                    :                                    "Regeneron Pharmaceuticals Inc."                                        ,               
        "TMUS"                      :                                                  "T-Mobile US Inc."                                                                    , 
                        "SBAC"                                      :                                  "SBA Communications Corp. Class A"                                    ,                 
                   "PH"                                 :                                       "Parker-Hannifin Corporation"                                                ,          
                  "FLT"                                :                                        "FleetCor Technologies Inc."                                                 ,          
         "ES"                       :                                                 "Eversource Energy"                                                                    ,
            "MCK"                          :                                              "McKesson Corporation"                                                             ,    
         "FE"                       :                                                 "FirstEnergy Corp."                                                                    ,
                    "LYB"                                  :                                      "LyondellBasell Industries NV"                                             ,            
          "IQV"                        :                                                "IQVIA Holdings Inc"                                                                 ,  
 "APTV"               :                                                         "Aptiv PLC"                                                                            ,
                "TSN"                              :                                          "Tyson Foods Inc. Class A"                                                     ,        
                 "DLR"                               :                                         "Digital Realty Trust Inc."                                                   ,         
                 "O"                               :                                         "Realty Income Corporation"                                                     ,       
   "XLNX"                 :                                                       "Xilinx Inc."                                                                          ,
                      "ADM"                                    :                                    "Archer-Daniels-Midland Company"                                         ,              
                    "ALXN"                                  :                                      "Alexion Pharmaceuticals Inc."                                            ,             
                   "SWK"                                 :                                       "Stanley Black & Decker Inc."                                               ,           
       "PPL"                     :                                                   "PPL Corporation"                                                                      ,
                                   "WLTW"                                                 :                       "Willis Towers Watson Public Limited Company"              ,                            
   "GLW"                 :                                                       "Corning Inc"                                                                          ,
            "EIX"                          :                                              "Edison International"                                                             ,    
                 "A"                               :                                         "Agilent Technologies Inc."                                                     ,       
                  "NTRS"                                :                                        "Northern Trust Corporation"                                                ,           
                         "PXD"                                       :                                 "Pioneer Natural Resources Company"                                   ,                 
           "ETR"                         :                                               "Entergy Corporation"                                                               ,   
            "VRSK"                          :                                              "Verisk Analytics Inc"                                                            ,     
           "SYF"                         :                                               "Synchrony Financial"                                                               ,   
               "IDXX"                             :                                           "IDEXX Laboratories Inc."                                                      ,        
                         "MCHP"                                       :                                 "Microchip Technology Incorporated"                                  ,                  
    "TWTR"                  :                                                      "Twitter Inc."                                                                         ,
                      "HPE"                                    :                                    "Hewlett Packard Enterprise Co."                                         ,              
            "MTB"                          :                                              "M&T Bank Corporation"                                                             ,    
          "DTE"                        :                                                "DTE Energy Company"                                                                 ,  
           "FITB"                         :                                               "Fifth Third Bancorp"                                                              ,    
   "VTR"                 :                                                       "Ventas Inc."                                                                          ,
                              "HIG"                                            :                            "Hartford Financial Services Group Inc."                         ,                      
                    "MNST"                                  :                                      "Monster Beverage Corporation"                                            ,             
             "LVS"                           :                                             "Las Vegas Sands Corp."                                                           ,     
           "CNC"                         :                                               "Centene Corporation"                                                               ,   
   "AME"                 :                                                       "AMETEK Inc."                                                                          ,
          "CTAS"                        :                                                "Cintas Corporation"                                                                ,   
            "WY"                          :                                              "Weyerhaeuser Company"                                                              ,   
        "BLL"                      :                                                  "Ball Corporation"                                                                     ,
  "KR"                :                                                        "Kroger Co."                                                                           ,
     "FTV"                   :                                                     "Fortive Corp."                                                                        ,
          "CERN"                        :                                                "Cerner Corporation"                                                                ,   
                         "AWK"                                       :                                 "American Water Works Company Inc."                                   ,                 
        "FAST"                      :                                                  "Fastenal Company"                                                                    , 
       "HSY"                     :                                                   "Hershey Company"                                                                      ,
                "ROK"                              :                                          "Rockwell Automation Inc."                                                     ,        
                     "UAL"                                   :                                     "United Airlines Holdings Inc."                                           ,             
         "MSCI"                       :                                                 "MSCI Inc. Class A"                                                                  ,  
                 "AMP"                               :                                         "Ameriprise Financial Inc."                                                   ,         
                 "ESS"                               :                                         "Essex Property Trust Inc."                                                   ,         
           "KHC"                         :                                               "Kraft Heinz Company"                                                               ,   
   "RMD"                 :                                                       "ResMed Inc."                                                                          ,
     "SNPS"                   :                                                     "Synopsys Inc."                                                                        ,
              "BXP"                            :                                            "Boston Properties Inc."                                                         ,      
                    "RCL"                                  :                                      "Royal Caribbean Cruises Ltd."                                             ,            
                        "MKC"                                      :                                  "McCormick & Company Incorporated"                                     ,                
   "CTVA"                 :                                                       "Corteva Inc"                                                                          ,
     "VRSN"                   :                                                     "VeriSign Inc."                                                                        ,
                 "KEYS"                               :                                         "Keysight Technologies Inc"                                                  ,          
"KEY"             :                                                           "KeyCorp"                                                                             ,
 "CDW"               :                                                         "CDW Corp."                                                                         ,  
  "ANSS"                :                                                        "ANSYS Inc."                                                                      ,    
                   "CMG"                                 :                                       "Chipotle Mexican Grill Inc."                                     ,                    
             "ALGN"                           :                                             "Align Technology Inc."                                                ,               
                   "CDNS"                                 :                                       "Cadence Design Systems Inc."                                    ,                     
           "FRC"                         :                                               "First Republic Bank"                                                     ,            
      "CLX"                    :                                                    "Clorox Company"                                                               ,       
               "CBRE"                             :                                           "CBRE Group Inc. Class A"                                            ,                 
        "HES"                      :                                                  "Hess Corporation"                                                           ,         
          "AEE"                        :                                                "Ameren Corporation"                                                       ,           
                "VMC"                              :                                          "Vulcan Materials Company"                                           ,                 
           "HAL"                         :                                               "Halliburton Company"                                                     ,            
              "RSG"                            :                                            "Republic Services Inc."                                               ,               
            "CCL"                          :                                              "Carnival Corporation"                                                   ,             
                   "IP"                                 :                                       "International Paper Company"                                      ,                   
                         "MTD"                                       :                                 "Mettler-Toledo International Inc."                         ,                          
         "BBY"                       :                                                 "Best Buy Co. Inc."                                                         ,          
         "OMC"                       :                                                 "Omnicom Group Inc"                                                         ,          
                            "ARE"                                          :                              "Alexandria Real Estate Equities Inc."                   ,                             
        "DHI"                      :                                                  "D.R. Horton Inc."                                                           ,         
                     "CFG"                                   :                                     "Citizens Financial Group Inc."                                 ,                      
               "SWKS"                             :                                           "Skyworks Solutions Inc."                                            ,                 
              "CMS"                            :                                            "CMS Energy Corporation"                                               ,               
         "NUE"                       :                                                 "Nucor Corporation"                                                         ,          
                     "RF"                                   :                                     "Regions Financial Corporation"                                  ,                     
                 "AJG"                               :                                         "Arthur J. Gallagher & Co."                                         ,                  
                        "CINF"                                      :                                  "Cincinnati Financial Corporation"                          ,                          
                  "PEAK"                                :                                        "Healthpeak Properties Inc."                                      ,                    
                "CHD"                              :                                          "Church & Dwight Co. Inc."                                           ,                 
   "CPRT"                 :                                                       "Copart Inc."                                                                    ,     
             "FCX"                           :                                             "Freeport-McMoRan Inc."                                                 ,              
                  "LEN"                                :                                        "Lennar Corporation Class A"                                       ,                   
                      "MXIM"                                    :                                    "Maxim Integrated Products Inc."                              ,                        
                                  "LH"                                                :                        "Laboratory Corporation of America Holdings"        ,                                  
    "EFX"                  :                                                      "Equifax Inc."                                                                   ,     
                 "MGM"                               :                                         "MGM Resorts International"                                         ,                  
                      "MLM"                                    :                                    "Martin Marietta Materials Inc."                               ,                       
 "AMCR"               :                                                         "Amcor PLC"                                                                        ,   
       "K"                     :                                                   "Kellogg Company"                                                               ,      
         "DOV"                       :                                                 "Dover Corporation"                                                         ,          
            "CAH"                          :                                              "Cardinal Health Inc."                                                   ,             
   "KMX"                 :                                                       "CarMax Inc."                                                                     ,    
                   "WDC"                                 :                                       "Western Digital Corporation"                                     ,                    
            "CE"                          :                                              "Celanese Corporation"                                                    ,            
                          "HBAN"                                        :                                "Huntington Bancshares Incorporated"                      ,                            
             "TFX"                           :                                             "Teleflex Incorporated"                                                 ,              
             "GPC"                           :                                             "Genuine Parts Company"                                                 ,              
            "KSU"                          :                                              "Kansas City Southern"                                                   ,             
                              "MAA"                                            :                            "Mid-America Apartment Communities Inc."               ,                               
                  "WCG"                                :                                        "WellCare Health Plans Inc."                                       ,                   
   "EVRG"                 :                                                       "Evergy Inc."                                                                    ,     
          "INCY"                        :                                                "Incyte Corporation"                                                      ,            
             "CXO"                           :                                             "Concho Resources Inc."                                                 ,              
             "COO"                           :                                             "Cooper Companies Inc."                                                 ,              
               "CNP"                             :                                           "CenterPoint Energy Inc."                                             ,                
                      "PFG"                                    :                                    "Principal Financial Group Inc."                               ,                       
                    "BKR"                                  :                                      "Baker Hughes Company Class A"                                   ,                     
       "ULTA"                     :                                                   "Ulta Beauty Inc"                                                            ,         
                                       "WAB"                                                     :                   "Westinghouse Air Brake Technologies Corporation"   ,                                 
        "CTL"                      :                                                  "CenturyLink Inc."                                                                 ,  
                               "IFF"                                             :                           "International Flavors & Fragrances Inc."                   ,                         
    "IT"                  :                                                      "Gartner Inc."                                                                         ,
          "GWW"                        :                                                "W.W. Grainger Inc."                                                             ,    
          "WAT"                        :                                                "Waters Corporation"                                                             ,    
   "NTAP"                 :                                                       "NetApp Inc."                                                                          ,
                "AKAM"                              :                                          "Akamai Technologies Inc."                                                ,           
"UDR"              :                                                          "UDR Inc."                                                                             ,
           "NLOK"                         :                                               "NortonLifeLock Inc."                                                          ,      
               "DRI"                             :                                           "Darden Restaurants Inc."                                                   ,         
  "XYL"                :                                                        "Xylem Inc."                                                                           ,
                           "BR"                                         :                               "Broadridge Financial Solutions Inc."                            ,                    
              "STX"                            :                                            "Seagate Technology PLC"                                                     ,        
   "GRMN"                 :                                                       "Garmin Ltd."                                                                          ,
                "EXR"                              :                                          "Extra Space Storage Inc."                                                 ,          
          "EXPE"                        :                                                "Expedia Group Inc."                                                            ,     
           "CTXS"                         :                                               "Citrix Systems Inc."                                                          ,      
                      "DGX"                                    :                                    "Quest Diagnostics Incorporated"                                     ,                
           "CAG"                         :                                               "Conagra Brands Inc."                                                           ,     
     "TIF"                   :                                                     "Tiffany & Co."                                                                       ,
         "MAS"                       :                                                 "Masco Corporation"                                                               ,   
     "FTNT"                   :                                                     "Fortinet Inc."                                                                      ,
         "L"                       :                                                 "Loews Corporation"                                                                 , 
                                   "EXPD"                                                 :                       "Expeditors International of Washington Inc."          ,                              
                 "MKTX"                               :                                         "MarketAxess Holdings Inc."                                              ,            
                          "TTWO"                                        :                                "Take-Two Interactive Software Inc."                            ,                     
                     "JEC"                                   :                                     "Jacobs Engineering Group Inc."                                       ,               
               "CBOE"                             :                                           "Cboe Global Markets Inc"                                                  ,          
            "XRAY"                          :                                              "DENTSPLY SIRONA Inc."                                                        ,       
                     "ABC"                                   :                                     "AmerisourceBergen Corporation"                                       ,               
       "FMC"                     :                                                   "FMC Corporation"                                                                   , 
                "ATO"                              :                                          "Atmos Energy Corporation"                                                 ,          
               "DRE"                             :                                           "Duke Realty Corporation"                                                   ,         
           "SIVB"                         :                                               "SVB Financial Group"                                                          ,      
               "CBS"                             :                                           "CBS Corporation Class B"                                                   ,         
                  "HST"                                :                                        "Host Hotels & Resorts Inc."                                             ,            
    "HOLX"                  :                                                      "Hologic Inc."                                                                        ,
               "FANG"                             :                                           "Diamondback Energy Inc."                                                  ,          
               "FOXA"                             :                                           "Fox Corporation Class A"                                                  ,          
                    "LNC"                                  :                                      "Lincoln National Corporation"                                         ,              
                    "AAL"                                  :                                      "American Airlines Group Inc."                                         ,              
            "SJM"                          :                                              "J.M. Smucker Company"                                                         ,      
               "AAP"                             :                                           "Advance Auto Parts Inc."                                                   ,         
           "LNT"                         :                                               "Alliant Energy Corp"                                                           ,     
            "WYNN"                          :                                              "Wynn Resorts Limited"                                                        ,       
  "QRVO"                :                                                        "Qorvo Inc."                                                                           ,
        "IEX"                      :                                                  "IDEX Corporation"                                                                ,  
             "WU"                           :                                             "Western Union Company"                                                       ,      
                        "BF.B"                                      :                                  "Brown-Forman Corporation Class B"                               ,                   
   "NDAQ"                 :                                                       "Nasdaq Inc."                                                                         ,
            "LDOS"                          :                                              "Leidos Holdings Inc."                                                       ,       
"NVR"              :                                                          "NVR Inc."                                                                             ,
           "URI"                         :                                               "United Rentals Inc."                                                          ,     
       "AES"                     :                                                   "AES Corporation"                                                                  , 
                 "LW"                               :                                         "Lamb Weston Holdings Inc."                                               ,          
                "EMN"                              :                                          "Eastman Chemical Company"                                                ,          
                              "UHS"                                            :                            "Universal Health Services Inc. Class B"                    ,                        
                    "JKHY"                                  :                                      "Jack Henry & Associates Inc."                                       ,               
              "TSCO"                            :                                            "Tractor Supply Company"                                                   ,         
                "HRL"                              :                                          "Hormel Foods Corporation"                                                ,          
                           "NCLH"                                         :                               "Norwegian Cruise Line Holdings Ltd."                         ,                      
                   "VAR"                                 :                                       "Varian Medical Systems Inc."                                          ,             
    "ARNC"                  :                                                      "Arconic Inc."                                                                       ,
                  "AVY"                                :                                        "Avery Dennison Corporation"                                            ,            
                    "RJF"                                  :                                      "Raymond James Financial Inc."                                        ,              
   "HAS"                 :                                                       "Hasbro Inc."                                                                          ,
                   "REG"                                 :                                       "Regency Centers Corporation"                                          ,             
    "TXT"                  :                                                      "Textron Inc."                                                                        ,
       "LKQ"                     :                                                   "LKQ Corporation"                                                                  , 
                    "CHRW"                                  :                                      "C.H. Robinson Worldwide Inc."                                       ,               
    "ALLE"                  :                                                      "Allegion PLC"                                                                       ,
             "CMA"                           :                                             "Comerica Incorporated"                                                      ,       
                        "PKG"                                      :                                  "Packaging Corporation of America"                                ,                  
             "RE"                           :                                             "Everest Re Group Ltd."                                                       ,      
            "ANET"                          :                                              "Arista Networks Inc."                                                       ,       
                     "ETFC"                                   :                                     "E*TRADE Financial Corporation"                                     ,                
                          "HII"                                        :                                "Huntington Ingalls Industries Inc."                            ,                    
         "HSIC"                       :                                                 "Henry Schein Inc."                                                             ,    
                         "JBHT"                                       :                                 "J.B. Hunt Transport Services Inc."                             ,                    
            "VNO"                          :                                              "Vornado Realty Trust"                                                        ,      
                   "CF"                                 :                                       "CF Industries Holdings Inc."                                           ,            
       "NRG"                     :                                                   "NRG Energy Inc."                                                                  , 
                "MRO"                              :                                          "Marathon Oil Corporation"                                                ,          
                            "TAP"                                          :                              "Molson Coors Brewing Company Class B"                        ,                      
        "WRK"                      :                                                  "WestRock Company"                                                                ,  
              "DISCK"                            :                                            "Discovery Inc. Class C"                                                  ,          
       "GL"                     :                                                   "Globe Life Inc."                                                                   ,
         "NBL"                       :                                                 "Noble Energy Inc."                                                              ,   
    "NI"                  :                                                      "NiSource Inc"                                                                         ,
                         "PNW"                                       :                                 "Pinnacle West Capital Corporation"                              ,                   
    "ABMD"                  :                                                      "ABIOMED Inc."                                                                       ,
             "WHR"                           :                                             "Whirlpool Corporation"                                                      ,       
       "PHM"                     :                                                   "PulteGroup Inc."                                                                  , 
        "PKI"                      :                                                  "PerkinElmer Inc."                                                                ,  
          "IRM"                        :                                                "Iron Mountain Inc."                                                            ,    
       "BWA"                     :                                                   "BorgWarner Inc."                                                                  , 
            "SNA"                          :                                              "Snap-on Incorporated"                                                        ,      
                       "FRT"                                     :                                   "Federal Realty Investment Trust"                                  ,                 
                "DVN"                              :                                          "Devon Energy Corporation"                                                 ,
              "MHK"                            :                                            "Mohawk Industries Inc."                                                     ,
                 "ZION"                               :                                         "Zions Bancorporation N.A."                                              ,
          "KSS"                        :                                                "Kohl's Corporation"                                                             ,
          "APA"                        :                                                "Apache Corporation"                                                             ,
                   "NOV"                                 :                                       "National Oilwell Varco Inc."                                           , 
        "FFIV"                      :                                                  "F5 Networks Inc."                                                                ,
             "JNPR"                           :                                             "Juniper Networks Inc."                                                      ,
                           "IPG"                                         :                               "Interpublic Group of Companies Inc."                           ,         
  "MYL"                :                                                        "Mylan N.V."                                                                           ,
             "ALK"                           :                                             "Alaska Air Group Inc."                                                       ,
                "KIM"                              :                                          "Kimco Realty Corporation"                                                 ,
      "FTI"                    :                                                    "TechnipFMC Plc"                                                                     ,
                           "FBHS"                                         :                               "Fortune Brands Home & Security Inc."                          ,          
                        "DISH"                                      :                                  "DISH Network Corporation Class A"                                ,       
                 "HFC"                               :                                         "HollyFrontier Corporation"                                               ,
               "BEN"                             :                                           "Franklin Resources Inc."                                                   ,
           "VIAB"                         :                                               "Viacom Inc. Class B"                                                          ,
                                           "AIV"                                                        :               "Apartment Investment and Management Company Class A",                                  
     "AIZ"                   :                                                     "Assurant Inc."                                                               ,        
             "CPB"                           :                                             "Campbell Soup Company"                                               ,                
     "TPR"                   :                                                     "Tapestry Inc."                                                               ,        
                   "COG"                                 :                                       "Cabot Oil & Gas Corporation"                                   ,                      
         "NWL"                       :                                                 "Newell Brands Inc"                                                       ,            
          "DXC"                        :                                                "DXC Technology Co."                                                     ,             
             "ALB"                           :                                             "Albemarle Corporation"                                               ,                
 "PVH"               :                                                         "PVH Corp."                                                                       ,    
   "PNR"                 :                                                       "Pentair plc"                                                                   ,      
      "MOS"                    :                                                    "Mosaic Company"                                                             ,         
               "AOS"                             :                                           "A. O. Smith Corporation"                                           ,                  
                    "LEG"                                  :                                      "Leggett & Platt Incorporated"                                 ,                       
         "FLIR"                       :                                                 "FLIR Systems Inc."                                                      ,             
                  "XRX"                                :                                        "Xerox Holdings Corporation"                                     ,                     
             "SLG"                           :                                             "SL Green Realty Corp."                                               ,                
    "IVZ"                  :                                                      "Invesco Ltd."                                                                 ,       
            "NLSN"                          :                                              "Nielsen Holdings Plc"                                                ,                
                      "RHI"                                    :                                    "Robert Half International Inc."                             ,                         
       "PRGO"                     :                                                   "Perrigo Co. Plc"                                                          ,           
   "DVA"                 :                                                       "DaVita Inc."                                                                   ,      
                      "PBCT"                                    :                                    "People's United Financial Inc."                            ,                          
             "FLS"                           :                                             "Flowserve Corporation"                                               ,                
            "PWR"                          :                                              "Quanta Services Inc."                                                 ,               
            "HOG"                          :                                              "Harley-Davidson Inc."                                                 ,               
  "UNM"                :                                                        "Unum Group"                                                                     ,     
              "SEE"                            :                                            "Sealed Air Corporation"                                             ,                 
                        "RL"                                      :                                  "Ralph Lauren Corporation Class A"                          ,                          
        "HBI"                      :                                                  "Hanesbrands Inc."                                                         ,           
    "ROL"                  :                                                      "Rollins Inc."                                                                 ,       
               "FOX"                             :                                           "Fox Corporation Class B"                                           ,                  
              "CPRI"                            :                                            "Capri Holdings Limited"                                            ,                  
                 "IPGP"                               :                                         "IPG Photonics Corporation"                                      ,                     
      "HRB"                    :                                                    "H&R Block Inc."                                                             ,         
  "M"                :                                                        "Macy's Inc"                                                                       ,   
                "NWSA"                              :                                          "News Corporation Class A"                                        ,                    
              "DISCA"                            :                                            "Discovery Inc. Class A"                                           ,                   
          "XEC"                        :                                                "Cimarex Energy Co."                                                     ,             
              "HP"                            :                                            "Helmerich & Payne Inc."                                              ,                
                      "AMG"                                    :                                    "Affiliated Managers Group Inc."                             ,                         
                         "ADS"                                       :                                 "Alliance Data Systems Corporation"                       ,                            
     "LB"                   :                                                     "L Brands Inc."                                                                ,       
         "COTY"                       :                                                 "Coty Inc. Class A"                                                      ,             
      "JWN"                    :                                                    "Nordstrom Inc."                                                             ,         
"GPS"              :                                                          "Gap Inc."                                                                         ,   
                 "UAA"                               :                                         "Under Armour Inc. Class A"                                       ,                    
        "TRIP"                      :                                                  "TripAdvisor Inc."                                                        ,            
                 "UA"                               :                                         "Under Armour Inc. Class C"                                        ,                   
        "MAC"                      :                                                  "Macerich Company"                                                         ,           
                "NWS"                                 :                                          "News Corporation Class B"                                      ,                      
};
if(props.list.length >0){
  for(let i = 0; i< props.list.length; i++){
    arr_favs.push(<StockBox key={i} togglePopup={props.togglePopup} stockName={snp500[props.list[i]]} stockSymbol ={props.list[i]}/>)
  }
}


return(
  <div>
    {arr_favs}

  </div>
)
}
export default RenderList;